# Configuration du projet
files:
  input_data: "input/data_test.csv"
  output: "output/"
  encoding: "UTF-8"
  separator: "," 
  dec: "."

report:
  title: "Rapport d'Analyse Questionnaire"
  author: "Groupe SAE but SD"
  date: true 

Parametrage:
  correlation: "80"
  supprimer_NA : false

columns:
  - name: "date_entree"
    type: "date"
    label: "Date d'arrivée"
    format: "%Y-%m-%d"



